using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GabrielWoWCompanionApp.Services;

public class TalentService
{
    public static ObservableCollection<Talent> GetDisciplineTalents()
    {
        var talents = new ObservableCollection<Talent>
        {
            new() { Id = 0, Name = "Unbreakable Will", MaxRank = 5, DescriptionTemplate = "Reduces the duration of Stun, Fear, and Silence effects done to you by an additional {0}%.", TalentModifier = 6, IconPath = "unbreakable_will_icon.jpg"},

            new() { Id = 1, Name = "Twin Disciplines", MaxRank = 5, DescriptionTemplate = "Increases the damage and healing done by your instant spells by {0}%.", TalentModifier = 1, IconPath = "twin_disciplines_icon.jpg" },

            new() { Id = 2, Name = "Silent Resolve", MaxRank = 3, DescriptionTemplate = "Reduces the threat generated by your Holy and Discipline spells by {0}% and reduces the chance your helpful spells and damage over time effects will be dispelled by {1}%.", TalentModifier = 6.755, TalentModifier2= 10, TotalRequiredTalents = 5, IconPath = "silent_resolve_icon.jpg" },

            new() { Id = 3, Name = "Improved Inner Fire", MaxRank = 3, DescriptionTemplate = "Increases the effect of your Inner Fire spell by {0}%, and increases the total number of charges by {1}.", TalentModifier = 15, TalentModifier2 = 4, TotalRequiredTalents = 5, IconPath = "inner_fire_icon.jpg" },

            new() { Id = 4, Name = "Improved Power Word: Fortitude", MaxRank = 2, DescriptionTemplate = "Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by {0}%, and increases your total stamina by {1}%.", TalentModifier = 15, TalentModifier2 = 2, TotalRequiredTalents = 5, IconPath = "fortitude_icon.jpg" },

            new() { Id = 5, Name = "Martyrdom", MaxRank = 2, DescriptionTemplate = "Gives you a {0}% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike.  The Focused Casting effect reduces the pushback suffered from damaging attacks while casting Priest spells and decreases the duration of Interrupt effects by {1}%.", TalentModifier = 50, TalentModifier2 = 10, TotalRequiredTalents = 5, IconPath = "desperate_prayer_icon.jpg" },

            new() { Id = 6, Name = "Meditation", MaxRank = 3, DescriptionTemplate = "Allows {0}% of your mana regeneration to continue while casting.", TalentModifier = 16.775, TotalRequiredTalents = 10, IconPath = "meditation_icon.jpg" },

            new() { Id = 7, Name = "Inner Focus", MaxRank = 1, DescriptionTemplate = "When activated, reduces the mana cost of your next spell by 100% and increases its critical effect chance by 25% if it is capable of a critical effect.", TotalRequiredTalents = 10, IconPath = "inner_focus_icon.jpg" },

            new() { Id = 8, Name = "Improved Power Word: Shield", MaxRank = 3, DescriptionTemplate = "Increases the damage absorbed by your Power Word: Shield by {0}%.", TalentModifier = 5, TotalRequiredTalents = 10, IconPath = "pws_icon.jpg" },

            new() { Id = 9, Name = "Absolution", MaxRank = 3, DescriptionTemplate = "Reduces the mana cost of your Dispel Magic, Cure Disease, Abolish Disease and Mass Dispel spells by {0}%.", TalentModifier = 5, TotalRequiredTalents = 15, IconPath = "absolution_icon.jpg" },

            new() { Id = 10, Name = "Mental Agility", MaxRank = 3, DescriptionTemplate = "Reduces the mana cost of your instant cast spells by {0}%.", TalentModifier = 3.33, TotalRequiredTalents = 15, IconPath = "mental_agility_icon.jpg"  },

            new() { Id = 11, Name = "Improved Mana Burn", MaxRank = 2, DescriptionTemplate = "Reduces the casting time of your Mana Burn spell by {0} sec.", TalentModifier = .5, TotalRequiredTalents = 15, IconPath = "mana_burn_icon.jpg" },

            new() { Id = 12, Name = "Reflective Shield", MaxRank = 2, DescriptionTemplate = "Causes {0}% of the damage you absorb with Power Word: Shield to reflect back at the attacker.  This damage causes no threat.", TalentModifier = 22.5, TotalRequiredTalents = 20, IconPath = "pws_icon.jpg" },

            new() { Id = 13, Name = "Mental Strength", MaxRank = 5, DescriptionTemplate = "Increases spell power by {0}% of your total Spirit.", TalentModifier = 3, TotalRequiredTalents = 20, IconPath = "mental_strength_icon.jpg" },

            new() { Id = 14, Name = "Soul Warding", MaxRank = 1, DescriptionTemplate = "Reduces the cooldown of your Power Word: Shield ability by 4 sec, and reduces the mana cost of your Power Word: Shield by {0}%.", TalentModifier = 15, TotalRequiredTalents = 20, IconPath = "soul_warding_icon.jpg" },

            new() { Id = 15, Name = "Focused Power", MaxRank = 2, DescriptionTemplate = "Increases damage and healing done by your spells by {0}%. In addition, your Mass Dispel cast time is reduced by {1} sec.", TalentModifier = 2, TalentModifier2 = .5, TotalRequiredTalents = 25, IconPath = "focused_power_icon.jpg" },

            new() { Id = 16, Name = "Enlightenment", MaxRank = 3, DescriptionTemplate = "Increases your total Spirit by {0}% and increases your spell haste by {0}%.", TalentModifier = 2, TotalRequiredTalents = 25, IconPath = "enlightenment_icon.jpg" },

            new() { Id = 17, Name = "Focused Will", MaxRank = 3, DescriptionTemplate = "Increases your spell critical effect chance by {0}%, and after taking a critical hit you gain the Focused Will effect, reducing all damage taken by {1}% and increasing healing effects on you by {2}%.  Stacks up to 3 times.  Lasts 8 sec.", TalentModifier = 1, TalentModifier2 = 1, TalentModifier3 = 1, TotalRequiredTalents = 30, IconPath = "focused_will_icon.jpg" },

            new() { Id = 18, Name = "Power Infusion", MaxRank = 1, DescriptionTemplate = "Infuses the target with power, increasing spell casting speed by 20% and reducing the mana cost of all spells by 20%.  Lasts 15 sec.", TotalRequiredTalents = 30, IconPath = "power_infusion_icon.jpg"},

            new() { Id = 19, Name = "Improved Flash Heal", MaxRank = 3, TalentModifier = 5, TalentModifier2 = 3.33, DescriptionTemplate = "Reduces the mana cost of your Flash Heal by {0}%, and increases the critical effect chance of your Flash Heal by {1}% on friendly targets at or below 50% health.", TotalRequiredTalents = 30, IconPath = "imp_flash_heal_icon.jpg"},

            new() { Id = 20, Name = "Renewed Hope", MaxRank = 2, TalentModifier = 2, TalentModifier2 = 50, DescriptionTemplate = "Increases the critical effect chance of your Flash Heal, Greater Heal and Penance (Heal) spells by {0}% on targets afflicted by the Weakened Soul effect, and you have a {1}% chance to reduce all damage taken by 3% for 1 min to all friendly party and raid targets when you cast Power Word: Shield. This effect has a 2 sec cooldown.", TotalRequiredTalents = 35, IconPath = "renewed_hope_icon.jpg" },

            new() { Id = 21, Name = "Rapture", MaxRank = 3 , DescriptionTemplate = "When your Power Word: Shield is completely absorbed or dispelled you are instantly energized with {0}% of your total mana, and you have a {1}% chance to energize your shielded target with 2% total mana, 8 rage, 16 energy or 32 runic power. This effect can only occur once every 12 sec.", TalentModifier = .5, TalentModifier2 = 33, TotalRequiredTalents = 35, IconPath = "rapture_icon.jpg" },

            new() { Id = 22, Name = "Aspiration", MaxRank = 2, DescriptionTemplate = "Reduces the cooldown of your Inner Focus, Power Infusion, Pain Suppression and Penance spells by {0}%.", TalentModifier = 10, TotalRequiredTalents = 35, IconPath = "aspiration_icon.jpg"},

            new() { Id = 23, Name = "Divine Aegis", MaxRank = 3, DescriptionTemplate = "Critical heals create a protective shield on the target, absorbing {0}% of the amount healed. Lasts 12 sec.", TalentModifier = 10, TotalRequiredTalents = 40, IconPath = "divine_aegis_icon.jpg" },

            new() { Id = 24, Name = "Pain Suppression", MaxRank = 1, DescriptionTemplate = "Instantly reduces a friendly target's threat by 5%, reduces all damage taken by 40% and increases resistance to Dispel mechanics by 65% for 8 sec.", TotalRequiredTalents = 40, IconPath = "pain_suppression_icon.jpg" },

            new() { Id = 25, Name = "Grace", MaxRank = 2, TalentModifier = 50, DescriptionTemplate = "Your Flash Heal, Greater Heal, and Penance spells have a {0}% change to bless the target with Grace, increasing all healing received from the Priest by 3%. This effect will stack up to 3 times. Grace can only be active on one target at a time.", TotalRequiredTalents = 40, IconPath = "grace_icon.jpg"},

            new() { Id = 26, Name = "Borrowed Time", MaxRank = 5, DescriptionTemplate = "Grants {0}% spell haste for your next spell after casting Power Word: Shield, and increases the amount absorbed by your Power Word: Shield equal to {1}% of your spell power.", TalentModifier= 5, TalentModifier2 = 8, TotalRequiredTalents = 45, IconPath = "borrowed_time_icon.jpg" },

            new() { Id = 27, Name = "Penance", MaxRank = 1, DescriptionTemplate = "Launches a volley of holy light at the target, causing 240 Holy damage to an enemy, or 670 to 756 healing to an ally instantly and every 1 sec for 2 sec.", TotalRequiredTalents = 50, IconPath = "penance_icon.jpg" }
        };

        talents[8].PreRequisitieTalent = talents[14];
        talents[13].PreRequisitieTalent = talents[18];
        talents[14].DependantTalent = talents[8];
        talents[18].DependantTalent = talents[13];
        return talents;
    }

    public static ObservableCollection<Talent> GetHolyTalents()
    {
        var talents = new ObservableCollection<Talent>
        {
            new() { Id = 0, Name = "Healing Focus", MaxRank = 2, DescriptionTemplate = "Reduces the pushback suffered from damaging attacks while casting any healing spell by {0}%.", TalentModifier = 35, IconPath = "healing_focus_icon.jpg"},
            
            new() { Id = 1, Name = "Improved Renew", MaxRank = 3, DescriptionTemplate = "Increases the amount healed by your Renew spell by {0}%.", TalentModifier = 5, IconPath = "renew_icon.jpg" },

            new() { Id = 2, Name = "Holy Specialization", MaxRank = 5, DescriptionTemplate = "Increases the critical effect chance of your Holy spells by {0}%.", TalentModifier = 1, IconPath = "holy_specialization_icon.jpg" },

            new() { Id = 3, Name = "Spell Warding", MaxRank = 5, DescriptionTemplate = "Reduces all spell damage taken by {0}%.", TalentModifier = 2, TotalRequiredTalents = 5, IconPath = "spellwarding_icon.jpg" },

            new() { Id = 4, Name = "Divine Fury", MaxRank = 5, DescriptionTemplate = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by {0} sec.", TalentModifier = 0.1, TotalRequiredTalents = 5, IconPath = "divine_fury_icon.jpg" },

            new() { Id = 5, Name = "Desperate Prayer", MaxRank = 1, DescriptionTemplate = "Instantly Heals the caster for 263 to 325.", TotalRequiredTalents = 10, IconPath = "desperate_prayer_icon.jpg" },

            new() { Id = 6, Name = "Blessed Recovery", MaxRank = 3, DescriptionTemplate = "After being struck by a melee or ranged critical hit, Blessed Recovery heals you for {0}% of the damage taken over 6 sec.  Additional critical hits taken during the effect increase the healing received.", TalentModifier = 5, TotalRequiredTalents = 10, IconPath = "blessed_recovery_icon.jpg" },

            new() { Id = 7, Name = "Inspiration", MaxRank = 3, DescriptionTemplate = "Reduces your target's physical damage taken by {0}% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, Binding Heal, Penance, Prayer of Mending, Prayer of Healing, or Circle of Healing spell.", TalentModifier = 3.33, TotalRequiredTalents = 10, IconPath = "inspiration_icon.jpg" },

            new() { Id = 8, Name = "Holy Reach", MaxRank = 2, DescriptionTemplate = "Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing, Holy Nova, Divine Hymn and Circle of Healing spells by {0}%.", TalentModifier = 10, TotalRequiredTalents = 15, IconPath = "holy_reach_icon.jpg" },

            new() { Id = 9, Name = "Improved Healing", MaxRank = 3, DescriptionTemplate = "Reduces the mana cost of your Lesser Heal, Heal, Greater Heal, Divine Hymn and Penance spells by {0}%.", TalentModifier = 5, TotalRequiredTalents = 15, IconPath = "improved_healing_icon.jpg" },

            new() { Id = 10, Name = "Searing Light", MaxRank = 2, DescriptionTemplate = "Increases the damage of your Smite, Holy Fire, Holy Nova and Penance spells by {0}%.", TalentModifier = 5, TotalRequiredTalents = 15, IconPath = "searing_light_icon.jpg"  },

            new() { Id = 11, Name = "Healing Prayers", MaxRank = 2, DescriptionTemplate = "Reduces the mana cost of your Prayer of Healing and Prayer of Mending spell by {0}%.", TalentModifier = 10, TotalRequiredTalents = 20, IconPath = "healing_prayers_icon.jpg" },

            new() { Id = 12, Name = "Spirit of Redemption", MaxRank = 1, DescriptionTemplate = "Increases total Spirit by {0}% and upon death, the priest becomes the Spirit of Redemption for 15 sec.  The Spirit of Redemption cannot move, attack, be attacked or targeted by any spells or effects.  While in this form the priest can cast any healing spell free of cost.  When the effect ends, the priest dies.", TalentModifier = 5, TotalRequiredTalents = 20, IconPath = "redemption_icon.jpg" },

            new() { Id = 13, Name = "Spiritual Guidance", MaxRank = 5, DescriptionTemplate = "Increases spell power by {0}% of your total Spirit.", TalentModifier = 5, TotalRequiredTalents = 20, IconPath = "spiritual_guidance_icon.jpg" },

            new() { Id = 14, Name = "Surge of Light", MaxRank = 2, DescriptionTemplate = "Your spell criticals have a {0}% chance to cause your next Smite or Flash Heal spell to be instant cast, cost no mana but be incapable of a critical hit.  This effect lasts 10 sec.", TalentModifier = 25, TotalRequiredTalents = 25, IconPath = "sol_icon.jpg" },

            new() { Id = 15, Name = "Spiritual Healing", MaxRank = 5, DescriptionTemplate = "Increases the amount healed by your healing spells by {0}%.", TalentModifier = 2, TotalRequiredTalents = 25, IconPath = "spiritual_healing_icon.jpg" },

            new() { Id = 16, Name = "Holy Concentration", MaxRank = 3, DescriptionTemplate = "Your mana regeneration from spirit is increased by {0}% for 8 sec after you critically heal with Flash Heal, Greater Heal, Binding Heal or Empowered Renew.", TalentModifier = 16.33, TotalRequiredTalents = 30, IconPath = "holy_concentration_icon.jpg" },

            new() { Id = 17, Name = "Lightwell", MaxRank = 1, DescriptionTemplate = "Creates a Holy Lightwell.  Friendly players can click the Lightwell to restore 819 health over 6 sec.  Attacks done to you equal to 30% of your total health will cancel the effect. Lightwell lasts for 3 min or 10 charges.", TotalRequiredTalents = 30, IconPath = "lightwell_icon.jpg" },

            new() { Id = 18, Name = "Blessed Resilience", MaxRank = 3, TalentModifier = 1, TalentModifier2 = 20, DescriptionTemplate = "Increases the effectiveness of your healing spells by {0}%, and critical hits made against you have a {1}% chance to prevent you from being critically hit again for 6 sec.", TotalRequiredTalents = 30, IconPath = "blessed_resilience_icon.jpg"},

            new() { Id = 19, Name = "Body and Soul", MaxRank = 2, TalentModifier = 30, TalentModifier2 = 50, DescriptionTemplate = "When you cast Power Word: Shield, you increase the target's movement speed by {0}% for 4 sec, and you have a {1}% chance when you cast Abolish Disease on yourself to also cleanse 1 poison effect in addition to diseases.", TotalRequiredTalents = 35, IconPath = "body_and_soul_icon.jpg"},

            new() { Id = 20, Name = "Empowered Healing", MaxRank = 5, TalentModifier = 8, TalentModifier2 = 4, DescriptionTemplate = "Your Greater Heal spell gains an additional {0}% and your Flash Heal and Binding Heal gain an additional {1}% of your bonus healing effects.", TotalRequiredTalents = 35, IconPath = "empowered_healing_icon.jpg" },

            new() { Id = 21, Name = "Serendipity", MaxRank = 3 , DescriptionTemplate = "When you heal with Binding Heal or Flash Heal, the cast time of your next Greater Heal or Prayer of Healing spell is reduced by {0}%. Stacks up to 3 times. Lasts 20 sec.", TalentModifier = 4, TotalRequiredTalents = 35, IconPath = "serendipity_icon.jpg" },

            new() { Id = 22, Name = "Empowered Renew", MaxRank = 3, DescriptionTemplate = "Your Renew spell gains an additional {0}% of your bonus healing effects, and your Renew will instantly heal the target for {0} of the total periodic effect.", TalentModifier = 5, TotalRequiredTalents = 40, IconPath = "empowered_renew_icon.jpg"},

            new() { Id = 23, Name = "Circle of Healing", MaxRank = 1, DescriptionTemplate = "Heals up to 5 friendly party or raid members within 15 yards of the target for 958 to 1058.", TotalRequiredTalents = 40, IconPath = "coh_icon.jpg" },

            new() { Id = 24, Name = "Test of Faith", MaxRank = 3, DescriptionTemplate = "Increases healing by {0}% on friendly targets at or below 50% health.", TalentModifier = 4, TotalRequiredTalents = 40, IconPath = "test_of_faith_icon.jpg" },

            new() { Id = 25, Name = "Divine Providence", MaxRank = 5, TalentModifier = 2, TalentModifier2 = 6, DescriptionTemplate = "Increases the amount healed by Circle of Healing, Binding Heal, Holy Nova, Prayer of Healing, Divine Hymn and Prayer of Mending by {0}%, and reduces the cooldown of your Prayer of Mending by {1}%.", TotalRequiredTalents = 45, IconPath = "divine_providence_icon.jpg"},

            new() { Id = 26, Name = "Guardian Spirit", MaxRank = 1, DescriptionTemplate = "Calls upon a guardian spirit to watch over the friendly target. The spirit increases the healing received by the target by 40%, and also prevents the target from dying by sacrificing itself.  This sacrifice terminates the effect but heals the target of 50% of their maximum health. Lasts 10 sec.", TotalRequiredTalents = 50, IconPath = "guardian_spirit_icon.jpg" }
        };

        talents[10].PreRequisitieTalent = talents[4];
        talents[17].PreRequisitieTalent = talents[12];
        talents[4].DependantTalent = talents[10];
        talents[12].DependantTalent = talents[17];
        return talents;
    }

    public static ObservableCollection<Talent> GetShadowTalents()
    {
        var talents = new ObservableCollection<Talent>
        {
            new() { Id = 0, Name = "Spirit Tap", MaxRank = 3, DescriptionTemplate = "Gives you a {0}% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your mana will regenerate at a 83% rate while casting.  Lasts 15 sec.%.", TalentModifier = 33.33, IconPath = "spirit_tap_icon.jpg"},

            new() { Id = 1, Name = "Improved Spirit Tap", MaxRank = 2, TalentModifier = 5, TalentModifier2 = 16.5, DescriptionTemplate = "Your Mind Blast and Shadow Word: Death critical strikes have a 100% chance and your Mind Flay critical strikes have a 50% chance to increase your total Spirit by {0}%. For the duration, your mana will regenerate at a {1}% rate while casting. Lasts 8 sec.", IconPath = "spirit_tap_icon.jpg" },

            new() { Id = 2, Name = "Darkness", MaxRank = 5, TalentModifier = 2, DescriptionTemplate = "Increases your Shadow spell damage by {0}%.", TotalRequiredTalents = 0, IconPath = "darkness_icon.jpg" },

            new() { Id = 3, Name = "Shadow Affinity", MaxRank = 3, TalentModifier = 8.33, TalentModifier2 = 5, DescriptionTemplate = "Reduces the threat generated by your Shadow spells by 25%, and you receive 15% of your base mana when your Shadow Word: Pain or Vampiric Touch spells are dispelled.", TotalRequiredTalents = 5, IconPath = "shadow_affinity_icon.jpg" },

            new() { Id = 4, Name = "Improved Shadow Word: Pain", MaxRank = 2, TalentModifier = 3, DescriptionTemplate = "Increases the damage of your Shadow Word: Pain spell by {0}%.", TotalRequiredTalents = 5, IconPath = "swp_icon.jpg" },

            new() { Id = 5, Name = "Shadow Focus", MaxRank = 3, TalentModifier = 1, TalentModifier2 = 2, DescriptionTemplate = "Increases your chance to hit with your Shadow spells by {0}%, and reduces the mana cost of your Shadow spells by {1}%.", TotalRequiredTalents = 5, IconPath = "shadow_focus_icon.jpg" },

            new() { Id = 6, Name = "Improved Psychic Scream", MaxRank = 2, TalentModifier = 2, DescriptionTemplate = "Reduces the cooldown of your Psychic Scream spell by {0} sec.", TotalRequiredTalents = 10, IconPath = "psychic_scream_icon.jpg" },

            new() { Id = 7, Name = "Improved Mind Blast", MaxRank = 5, TalentModifier = .5, TalentModifier2 = 20, DescriptionTemplate = "Reduces the cooldown of your Mind Blast spell by {0} sec., and while in Shadowform your Mind Blast also has a {1}% chance to reduce all healing done to the target by 20% for 10 sec.", TotalRequiredTalents = 10, IconPath = "mind_blast_icon.jpg" },

            new() { Id = 8, Name = "Mind Flay", MaxRank = 1, DescriptionTemplate = "Assault the target's mind with Shadow energy, causing 45 Shadow damage over 3 sec and slowing their movement speed by 50%.", TotalRequiredTalents = 10, IconPath = "mind_flay_icon.jpg" },

            new() { Id = 9, Name = "Vieled Shadows", MaxRank = 2, TalentModifier = 3, TalentModifier2 = 1, DescriptionTemplate = "Decreases the cooldown of your Fade ability by {0} sec, and reduces the cooldown of your Shadowfiend ability by {1} minutes.", TotalRequiredTalents = 15, IconPath = "fade_icon.jpg" },

            new() { Id = 10, Name = "Shadow Reach", MaxRank = 2, TalentModifier = 10, DescriptionTemplate = "Increases the range of your offensive Shadow spells by {0}%.", TotalRequiredTalents = 15, IconPath = "shadow_reach_icon.jpg"  },

            new() { Id = 11, Name = "Shadow Weaving", MaxRank = 3, TalentModifier = 33.33, DescriptionTemplate = "Your Shadow damage spells have a {0}% chance to increase the Shadow damage you deal by 2% for 15 sec.  Stacks up to 5 times.", TotalRequiredTalents = 15, IconPath = "shadow_weaving_icon.jpg" },

            new() { Id = 12, Name = "Silence", MaxRank = 1, DescriptionTemplate = "Silences the target, preventing them from casting spells for 5 sec.  Non-player victim spellcasting is also interrupted for 3 sec.", TotalRequiredTalents = 20, IconPath = "silence_icon.jpg" },

            new() { Id = 13, Name = "Vampiric Embrace", MaxRank = 1, DescriptionTemplate = "Fills you with the embrace of Shadow energy, causing you to be healed for 15% and other party members to be healed for 3% of any single-target Shadow spell damage you deal for 30 min.", TotalRequiredTalents = 20, IconPath = "vampiric_embrace_icon.jpg" },

            new() { Id = 14, Name = "Improved Vampiric Embrace", MaxRank = 2, TalentModifier = 33.33, DescriptionTemplate = "Increases the healing received from Vampiric Embrace by {0}%.", TotalRequiredTalents = 20, IconPath = "imp_vampiric_embrace_icon.jpg" },

            new() { Id = 15, Name = "Focused Mind", MaxRank = 3, TalentModifier = 5, DescriptionTemplate = "Reduces the mana cost of your Mind Blast, Mind Control, Mind Flay and Mind Sear spells by {0}%.", TotalRequiredTalents = 20, IconPath = "focused_mind_icon.jpg" },

            new() { Id = 16, Name = "Mind Melt", MaxRank = 2, TalentModifier = 2, TalentModifier2 = 3, DescriptionTemplate = "Increases the critical strike chance of your Mind Blast, Mind Flay and Mind Sear spells by {0}%, and increases the periodic critical strike chance of your Vampiric Touch, Devouring Plague and Shadow Word: Pain spells by {1}%.", TotalRequiredTalents = 25, IconPath = "mind_melt_icon.jpg" },

            new() { Id = 17, Name = "Improved Devouring Plague", MaxRank = 3, TalentModifier = 5, TalentModifier2 = 10, TalentModifier3 = 1, DescriptionTemplate = "Increases the periodic damage done by your Devouring Plague by {0}%, and when you cast Devouring Plague you instantly deal damage equal to {1}% of its total periodic effect.", TotalRequiredTalents = 25, IconPath = "devouring_plague_icon.jpg" },

            new() { Id = 18, Name = "Shadowform", MaxRank = 1, DescriptionTemplate = "Assume a Shadowform, increasing your Shadow damage by 15%, reducing all damage done to you by 15% and threat generated by 30%.  However, you may not cast Holy spells while in this form except Cure Disease and Abolish Disease.  Grants the periodic damage from your Shadow Word: Pain, Devouring Plague, and Vampiric Touch spells the ability to critically hit for 100% increased damage and grants Devouring Plague and Vampiric Touch the ability to benefit from haste.", TotalRequiredTalents = 35, IconPath = "shadowform_icon.jpg"},

            new() { Id = 19, Name = "Shadow Power", MaxRank = 5, TalentModifier = 20, DescriptionTemplate = "Increases the critical strike damage bonus of your Mind Blast, Mind Flay, and Shadow Word: Death spells by {0}%.", TotalRequiredTalents = 35, IconPath = "shadow_power_icon.jpg"},

            new() { Id = 20, Name = "Improved Shadowform", MaxRank = 2, TalentModifier = 50, TalentModifier2 = 35, DescriptionTemplate = "Your Fade ability now has a {0}% chance to remove all movement impairing effects when used while in Shadowform, and reduces casting or channeling time lost when damaged by {1}% when casting any Shadow spell while in Shadowform.", TotalRequiredTalents = 35, IconPath = "shadowform_icon.jpg" },

            new() { Id = 21, Name = "Misery", MaxRank = 3 , TalentModifier = 1, TalentModifier2 = 5, DescriptionTemplate = "Your Shadow Word: Pain, Mind Flay and Vampiric Touch spells also increase the chance for harmful spells to hit by {0}% lasting 24 sec, and increases the benefit from spell power gained by your Mind Blast, Mind Flay and Mind Sear spells by {1}%.", TotalRequiredTalents = 35, IconPath = "misery_icon.jpg" },

            new() { Id = 22, Name = "Psychic Horror", MaxRank = 1, DescriptionTemplate = "You terrify the target, causing them to tremble in horror for 3 sec and drop their main hand and ranged weapons for 10 sec.", TotalRequiredTalents = 40, IconPath = "psychic_horror_icon.jpg"},

            new() { Id = 23, Name = "Vampiric Touch", MaxRank = 1, DescriptionTemplate = "Causes 600 Shadow damage over 15 sec to your target and causes up to 10 party or raid members to gain 1% of their maximum mana per 5 sec when you deal damage from Mind Blast. In addition, if the Vampiric Touch is dispelled it will cause 960 damage to the afflicted target.", TotalRequiredTalents = 40, IconPath = "vampiric_touch_icon.jpg" },

            new() { Id = 24, Name = "Pain and Suffering", MaxRank = 3, TalentModifier = 33.33, TalentModifier2 = 10, DescriptionTemplate = "Your Mind Flay has a {0}% chance to refresh the duration of your Shadow Word: Pain on the target, and reduces the damage you take from your own Shadow Word: Death by {1}%.", TotalRequiredTalents = 40, IconPath = "p_n_s_icon.jpg" },

            new() { Id = 25, Name = "Twisted Faith", MaxRank = 5, TalentModifier = 4, TalentModifier2 = 2, DescriptionTemplate = "Increases your spell power by {0}% of your total Spirit, and your damage done by your Mind Flay and Mind Blast is increased by {1}% if your target is afflicted by your Shadow Word: Pain.", TotalRequiredTalents = 45, IconPath = "twisted_faith_icon.jpg"},

            new() { Id = 26, Name = "Dispersion", MaxRank = 1, DescriptionTemplate = "You disperse into pure Shadow energy, reducing all damage taken by 90%.  You are unable to attack or cast spells, but you regenerate 6% mana every 1 sec for 6 sec. Dispersion can be cast while stunned, feared or silenced and clears all snare and movement impairing effects when cast, and makes you immune to them while dispersed.", TotalRequiredTalents = 50, IconPath = "dispersion_icon.jpg" }
        };

        talents[1].PreRequisitieTalent = talents[0];
        talents[12].PreRequisitieTalent = talents[6];
        talents[14].PreRequisitieTalent = talents[13];
        talents[18].PreRequisitieTalent = talents[13];
        talents[20].PreRequisitieTalent = talents[18];
        talents[23].PreRequisitieTalent = talents[18];
        talents[26].PreRequisitieTalent = talents[23];

        talents[0].DependantTalent = talents[1];
        talents[6].DependantTalent = talents[12];
        talents[13].DependantTalent2 = talents[14];
        talents[13].DependantTalent = talents[18];
        talents[18].DependantTalent = talents[20];
        talents[18].DependantTalent2 = talents[23];
        talents[23].DependantTalent = talents[26];
        return talents;
    }
}
